### ISSUE TITLE
More races

### ISSUE THREAD

**Issue by Arctic0Reaper** [JohnWhy/DnD-Discord-Bot#79] opened 2021-02-16 05:06 UTC
I’m sure you’re working on it, but I need a war forged.

**Comment by JohnWhy** [comment] 2023-05-24 00:06
Duplicate of another race request, will be added soon:tm: Check out for now: https://github.com/JohnWhy/DnD-Discord-Bot/blob/master/Custom%20Race%20Creation.md

**Closed as completed by JohnWhy** 2023-05-24 00:06 UTC
